/**
 * English copy deck for the global board. Same shape as `copyId` (enforced by
 * CopyDeck). Keeps the panjat-pinang metaphor via English labels; money surfaces
 * stay plain and literal.
 */
import { formatCount, formatRupiah } from "@/lib/format";
import type { CopyDeck } from "./id";

export const copyEn: CopyDeck = {
  merek: {
    nama: "Panjat",
    tagline: "Seize the Top Spot",
    deskripsiSitus:
      "Drop your link, climb the board, and overtake whoever's above you. The stronger your grip, the higher you sit.",
  },

  // Site-level social share card (src/app/opengraph-image.tsx).
  og: {
    alt: "Panjat — a paid leaderboard. Seize the Top Spot.",
    subtitle:
      "Drop your link, climb the board, overtake those above. Everything slips every hour — the summit is always up for grabs.",
    footer: "a paid leaderboard · for indie makers & small businesses",
  },

  nav: {
    beranda: "Home",
    sepanjangMasa: "Main Board",
    hariIni: "Today",
    jelajah: "Explore",
    cari: "Search",
    manjat: "Climb",
    leaderboard: "Leaderboard",
    statistik: "Stats",
    arsip: "Archive",
    aturan: "Rules",
    papanRingkas: "Board",
  },

  beranda: {
    heroJudul: "Climb. Overtake. Be #1.",
    statOnline: "online",
    statPengunjung: "visitors",
    lihatStatistik: "See stats →",
    tabSepanjang: "All time",
    papanKosongJudul: "Nobody's climbed yet.",
    papanKosongPesan: "The pole is still spotless.",
    papanKosongCta: "Be the first up the pole",
    caraMainJudul: "How it works",
    punyaProduk: "Got a product?",
    heroUrlPlaceholder: "Drop the link you want to climb with",
    heroKategoriPlaceholder: "Category",
    heroCta: "Start Climbing",
  },

  caraMain: [
    ["1", "Drop your product link", "Title, description, and category fill in automatically."],
    ["2", "Pick a spot & pay", "The system works out the amount. Pay by card/e-wallet."],
    ["3", "Rise — then slip", "The pole is slippery, everyone slides down slowly. Climb again to hold on."],
  ],

  listing: {
    pratinjauAlt: (nama: string) => `Site preview for ${nama}`,
    // Share-card alt + fallback description (used when a listing has no bio).
    ogAlt: (nama: string, rank: number | null) =>
      `${nama} on the Panjat board${rank ? ` — rank #${rank}` : ""}`,
    ogDeskripsi: (nama: string) => `${nama} on the Panjat board. Overtake it to seize its spot.`,
  },

  papan: {
    aktivitas: "Activity",
    aktivitasVote: "just voted for",
    aktivitasDukung: "just supported",
    aktivitasManjat: "just climbed",
    aktivitasNaik: (rank: number) => `rose to #${rank}`,
    aktivitasKali: (n: number) => ` ${n}x`,
    puncakBerganti: (nama: string) => `Summit changed hands — ${nama} is now #1`,
    papanDiperbarui: "Board updated",
    koneksiPutus: "Live board connection dropped — trying to reconnect…",
    bukaTabBaru: "open in new tab",
    juaraKakiTiang: "Base of the Pole Champion this week · free",
    juaraTerfavorit: "Favorite climber last week",
    juaraTerfavoritVote: (n: number) => `${formatCount(n)} votes`,
    terfavoritPekanIni: "Favorite this week",
    dukunganTerbanyak: "Most supported",
    salip: (rp: string) => `Overtake for ${rp}`,
    salipRank: (rank: number, rp: string) => `Overtake #${rank} for ${rp}`,
    juara: (rank: number) => `Champion ${rank}`,
    salipSingkat: "Overtake",
    klik: (n: number) => `${formatCount(n)} clicks`,
    klikProof: "Real clicks sent to this site — counted on the server.",
    // Card rosot status (revealed on hover) — two states + the at-floor case.
    rosotTerjaga: "still holding",
    rosotAktif: (rp: string) => `slipping ~${rp}/day`,
    rosotLantai: "at the floor · not slipping",
    kunjungiSitus: "Visit site",
    salipDiPapan: "Overtake on the board",
    pagination: (hal: number, total: number) => `Page ${hal} / ${total}`,
    sebelumnya: "← Previous",
    berikutnya: "Next →",
  },

  manjat: {
    judul: "Climb the pole",
    kembaliPapan: "← Board",
    steps: ["Details", "Position", "Pay"],
    urlLabel: "URL",
    urlPlaceholder: "panjat.id",
    detailTerisi: "Details filled in",
    cekLink: "Checking link & filling in details…",
    hapusUrl: "Clear & rewrite",
    detailRingkas: "Title, category & description — tap to edit",
    posisiPrimer: "You'll pay",
    judulListing: "Title",
    judulPlaceholder: "Nyala Analytics",
    kategori: "Category",
    deskripsi: "Description (160 chars)",
    emailOpsional: "Email (optional)",
    emailPlaceholder: "you@email.com",
    emailHint: "Add it if you want dashboard access & notifications. No account needed.",
    gambarLabel: "Image URL (optional)",
    gambarPlaceholder: "https://…/photo.jpg",
    gambarHint: "Photo/logo for the card — e.g. your IG/TikTok profile picture. Leave blank for auto-detection.",
    lanjut: "Continue",
    kembali: "Back",
    kembaliPosisi: "Back to position",
    detail: "Details",
    ubahDetail: "edit details",
    manjatPrefix: "Climbing:",
    posisiTanya: "What position do you want? The system does the math.",
    pratinjauSitus: "Preview of your site",
    pratinjauAlt: (nama: string) => `Site preview for ${nama}`,
    nominalLabel: "Amount (USD)",
    nominalPlaceholder: "25.00",
    nominalTanya: "How much do you want to pay? Position is calculated automatically.",
    nominalNaik: "The more you pay, the higher you rank. Minimum $5.00.",
    manjatLagiHint: (saatIni: string, total: string) =>
      `Climb again — grip ${saatIni} + your payment becomes ${total}.`,
    nominalDinaikkan: (rp: string) => `Below the minimum — automatically raised to ${rp}.`,
    diPosisi: "You'll be at position",
    ketikNominal: "Type an amount to see your position on the board.",
    kamuBadge: "you",
    listingKamu: "Your listing",
    salipTambah: (extra: string, rank: number) => `Add ${extra} → overtake #${rank}`,
    jadiPuncak: "🚩 You're #1 — the summit!",
    papanPratinjau: "Your position on the board",
    posisiRingkas: (rosot: string, estimasiHari: number | null) =>
      `Slipping ~${rosot}/day · ` +
      (estimasiHari === null ? "stable (base of the pole)" : `holds ~${estimasiHari} days`),
    akanBayar: "You'll pay",
    bayar: (rp?: string) => (rp ? `Pay ${rp}` : "Pay"),
    bayarMinimal: (rp: string) => `Pay at least ${rp}`,
    consentSetuju: "I agree to the",
    consentKetentuan: "Terms",
    consentAturan: "Rules",
    consentRosot: ", and understand that grip can slip (drop) over time.",
    bayarQris: (rp: string) => `Pay ${rp} by card/e-wallet`,
    memproses: "Processing…",
    menghitung: "Calculating…",
    pilihTarget: "Pick a target position.",
    yakinBayar: (rp: string) => `I'm sure about paying ${rp}.`,
    diprosesJudul: "Payment processing",
    diprosesPesan: "Your position will appear on the board once payment is confirmed.",
    kePapan: "To the board",
    // Quote summary line under the amount selector.
    quoteRingkas: (rank: number, rosotRp: string, estimasiHari: number | null) =>
      `Position #${rank} · slipping ~${rosotRp}/day · ` +
      (estimasiHari === null ? "stable (base of the pole)" : `holds ~${estimasiHari} days`),
    ringkasListing: "Listing",
    ringkasTarget: "Target position",
    ringkasEstimasi: "Estimated hold",
    ringkasTotal: "Total",
    stabil: "stable",
    bertahanHari: (n: number) => `~${n} days`,
  },

  favorit: {
    judul: "Favorite climber",
    hadiah: "Champions are decided weekly and posted on Threads & TikTok.",
    labelBelumVote: "free vote · 1×/day",
    sudahVote: "already voted",
    ajakan: "Pick your favorite — not about money, about taste. Once a day.",
    pilihListing: "Pick a listing…",
    pilihLainnya: "Pick another",
    pilihJudul: "Pick a climber",
    terpilih: "Your pick",
    batalPilih: "Cancel pick",
    cari: "Search climbers…",
    takAda: "No matching listings.",
    vote: "Vote",
    voteMengirim: "Sending…",
    voteGagal: "Couldn't save your vote — try again.",
    vote_n: (n: number) => `${formatCount(n)} votes`,
    belumAda: "Be the first to receive a vote.",
  },

  kakiTiang: {
    judul: "Base of the Pole",
    sisaDukungan: (n: number) => `${n} supports left today`,
    ajakan:
      "Free listings — support the ones you think are good. Each week, the most-supported becomes the Base of the Pole Champion and rises onto the board.",
    dukung: "Support",
    dukungGagal: "Couldn't support — try again.",
    dukungan_n: (n: number) => `${formatCount(n)} supporters`,
    kosong: "Nobody's waiting yet, you've got no rivals",
    pasangGratisTaut: "List free at the Base of the Pole",
    baruNaik: "Your listing has risen to the Base of the Pole. Rally people to support it so it climbs!",
    baruTutup: "Close",
  },

  momen: {
    eyebrow: "Summit Moment",
    dipuncak: "You're at the summit!",
    naik: (rank: number) => `You rose to #${rank}`,
    ringkas: (nama: string, pegangan: string) => `${nama} · grip ${pegangan}`,
    menyalip: (n: number) => `overtook ${n} climbers`,
    share: (rank: number) => `I'm #${rank} on Panjat!`,
    kartuAlt: (nama: string) => `${nama} card`,
    siapkanPratinjau: "Preparing preview…",
    bagikanAjak: "Save & show it off 👇",
    lihatPapan: "See the leaderboard",
    pilihUkuran: "Pick a card size",
    unduh: "Download card",
    mengunduh: "Preparing…",
    tersimpan: "Card saved ✓",
    bagikan: "Share",
    tautanDisalin: "Link copied ✓",
    toggleScreenshot: "Screenshot",
    toggleLogo: "Logo",
    rasio: "Ratio",
    gambar: "Image",
  },

  privasi: {
    metaTitle: "Privacy Policy — Panjat",
    judul: "Privacy Policy",
    butir: [
      ["What we store.", " Your contact (email) for the dashboard and notifications. For clicks, we only store a hashed version of your IP address — not the real one — so it can't be traced back to you. The spectator features use an anonymous cookie that stores no personal data whatsoever."],
      ["How long we keep it.", " We delete raw click data after 13 months; only the daily rollup is kept permanently. Notification records are kept 6 months. We keep transaction data for as long as required for tax and audit purposes."],
      ["Your rights.", " You're free to stop receiving notifications at any time, and you can ask to have your contact data deleted — just let us know."],
    ],
    kontak: "Want your data deleted or have a privacy question? Email us at halo@panjat.id.",
    diperbarui: "Last updated August 30, 2026.",
  },

  ketentuan: {
    metaTitle: "Terms & Conditions — Panjat",
    judul: "Terms & Conditions",
    peganganTebal: "Grip & refunds.",
    peganganSisa:
      " Your rank is set by your grip. Grip you've already paid can't be refunded — unless your listing is rejected by moderation; if that happens, you get a full refund. Details are on the ",
    peganganLink: "Rules",
    butir: [
      ["Moderation & content.", " Gambling/slots, adult, illegal lending, and scam content are not accepted. If a listing breaks the rules, we can hold or take it down."],
      ["URL ownership.", " If you're the rightful owner of a URL, you have the right to claim its listing or ask for it to be taken down. We need to verify first."],
      ["Liability.", " Panjat only displays listings — the content and products are entirely the responsibility of each sponsor."],
      ["Contact.", " Questions about these terms? Email us at halo@panjat.id."],
    ],
    diperbarui: "Last updated August 30, 2026.",
  },

  jelajah: {
    cariPlaceholder: "Search AI tools, services, games…",
    cari: "Search",
    cariLabel: "Search listings",
    kembali: "← Back to Search",
    juaraKategori: "Category champion",
    diPapan: "on the board →",
    lihatDetail: "See details →",
    semua: "All",
    kosong: "No matching listings. Try another keyword or category.",
    kosongCari: (q: string) => `No results for “${q}”. Try another keyword.`,
    hasil: (n: number, q: string) => `${n} results for “${q}”`,
    semuaListing: (n: number) => `${n} listings`,
  },

  hariIni: {
    judul: "Today's Board",
    kosong: "Nobody's paid today yet. Today's champion spot is wide open.",
    metaTitle: "Today's Board — Panjat",
    metaDesc: "A board that resets every midnight. Anyone can be today's champion.",
    ogPemanjat: (n: number) => `${n} climbers that day`,
    ogKosong: "Yesterday's money doesn't count",
    ogReset: "resets every midnight",
  },

  statistik: {
    judul: "Stats",
    sub: "The plain numbers so you can weigh things up before you climb. All public, straight from our own data.",
    diperbarui: (waktu: string) => `Updated ${waktu} · recalculated every time this page is opened`,
    metaTitle: "Stats — Panjat",
    metaDesc: "Panjat's public numbers for anyone thinking of climbing: the current summit price, the cost to break into the top 20, clicks over the past week, CPC, sponsor count, and how often the summit changes hands.",
    hargaPuncak: "Current summit price",
    hargaPuncakSub: "to sit at #1",
    hargaPuncakMetode: "The grip currently held by champion #1, taken from the payment records.",
    hargaMasuk20: "Cost to break into the top 20",
    hargaMasuk20Sub: "grip at rank 20",
    hargaMasuk20Metode: "The grip of the listing currently sitting at rank 20.",
    hargaMasuk20Terbuka: "Still open",
    hargaMasuk20TerbukaSub: "top 20 slots not yet full",
    klikTotal: "Total clicks delivered",
    klikTotalMetode: "Counted on the server every time someone clicks a link, since the board opened. Repeat clicks from the same person within 6 hours aren't double-counted.",
    cpc: "Average CPC",
    cpcSub: "cost per click delivered",
    cpcMetode: "Total verified money in, divided by the number of link clicks, counted since day one.",
    sponsor: "Active sponsors",
    sponsorSub: "currently live on the board",
    sponsorMetode: "The number of listings currently live on the board.",
    puncakBerganti: "Summit changes (7 days)",
    puncakBergantiSub: "the more often, the easier to seize",
    puncakBergantiMetode: "How many times the #1 spot changed hands, from the hourly position records.",
    pengunjung: "Total visitors",
    pengunjungSub: "reach since the start",
    pengunjungMetode: "The number of distinct visitors, counted via a safe anonymous cookie — without storing any personal data.",
    online: "Online now",
    onlineSub: "currently viewing the board",
    onlineMetode: "Visitors active in the last few minutes.",
    ga4Lokasi: "Visitor location",
    ga4Perangkat: "Device",
    ga4Sumber: "This data comes from Google Analytics",
  },

  arsip: {
    judul: "Champions Archive",
    metaTitle: "Champions Archive — Panjat",
    metaDesc: "Every daily champion, kept permanently.",
    kosong: "No champions archived yet.",
    mingguanJudul: "Champions this week",
    mingguanPekan: (minggu: string) => `Week ${minggu}`,
    mingguanInfo: "Updated automatically each week, archived permanently.",
    harianJudul: "Daily champions",
    jenis: {
      papan1: "Champion 1",
      papan2: "Champion 2",
      papan3: "Champion 3",
      terfavorit: "Favorite",
      klik_terbanyak: "Most clicks",
      kaki_tiang: "Base of the Pole Champion",
    } as Record<string, string>,
  },

  aturan: {
    metaTitle: "Rules — Panjat",
    metaDesc: "How the slippery pole works — how fast you slip at each position, the example numbers, plus the rules on ranking and refunds.",
    judul: "Rules",
    intro:
      "You pay to climb, and whoever has the strongest grip sits at the very top. But the pole is slippery: everyone slowly slips down. To hold your place up top, just climb again.",
    tabelJudul: "How fast you slip each day",
    kolomPosisi: "Position",
    kolomRosot: "Slip / day",
    tierR1: "#1 (summit)",
    tierR2_3: "#2–3",
    tierR4_10: "#4–10",
    tierR11_30: "#11–30",
    tierR31: "#31 and below",
    tierKaki: (rp: string) => `Grip ≤ ${rp} (Base of the Pole)`,
    contoh: (grip: string, rosot: string, sisa: string) =>
      `Example: a grip of ${grip} at #1 slips ${rosot} per day. If you stop climbing, in ~5 days only ~${sisa} is left — and the summit opens up again for someone else.`,
    peringkatTebal: "Rank is decided purely by grip.",
    peringkatSisa: " No hidden algorithm, and no positions quietly sold outside the system.",
    refundTebal: "No refunds",
    refundSisa: " for grip you've already paid — unless your listing is rejected by moderation; if that happens, you get a full refund.",
    rosotServer: (rp: string) =>
      `Slip is calculated automatically on the server every hour. Grip stops slipping the moment it hits ${rp} (Base of the Pole), and your listing will never be deleted just for slipping.`,
    lantaiTebal: "What you've paid is protected.",
    lantaiSisa: (persen: string, maks: string) =>
      ` Your grip won't slip below ${persen} of the total you've paid (up to a maximum of ${maks}). So once you pay, you won't fall to the bottom — but the summit still has to be earned.`,
  },

  pasangGratis: {
    metaTitle: "List for free — Panjat",
    metaDesc: "Post a free listing at the Base of the Pole. Earn support from visitors.",
    judul: "List for free",
    subJudul: "Free listings at the Base of the Pole, ordered by visitor support.",
    urlPlaceholder: "myproduct.id",
    judulPlaceholder: "My Product",
    emailHint: "Add it if you want to manage the listing later.",
    tombol: "List at the Base of the Pole",
    sisaSlot: (sisa: number, total: number) =>
      `First come, first served — ${sisa} of ${total} free slots left this week.`,
    penuh: "Free slots for this week are full. Try again next week, or take a paid climb.",
  },

  dasbor: {
    judul: "Dashboard",
    keluar: "Log out",
    belumAdaListing: "No listings under this account yet.",
    manjatSekarang: "Climb now",
    masukJudul: "Log in to dashboard",
    masukSub: "Track your listing's grip, clicks, and CPC.",
    statPegangan: "Grip",
    statPosisi: "Position",
    statRosot: "Slip rate",
    statEstimasi: "Estimated hold",
    statKlik: "Clicks today",
    statCpc: "CPC",
    posisi7: "Position over 7 days",
    pratinjauSitus: "Site preview",
    segarkan: "Refresh preview",
    menyegarkan: "Refreshing…",
    pratinjauTersegarkan: "Preview updated ✓",
    belumAdaPratinjau: "No preview yet. Refresh to capture how your site looks.",
    deskripsi: "Description",
    riwayat: "Payment history",
    jagaJudul: "Auto-hold position",
    jagaKet: "The system climbs again automatically if you slip below your target — using a recurring card/e-wallet, not a balance. Stop any time.",
    jagaTarget: "Target",
    jagaTop1: "Stay #1",
    jagaTop3: "Stay Top 3",
    jagaTop10: "Stay Top 10",
    jagaBudget: "Add budget (USD)",
    jagaSisa: (rp: string) => `Budget left: ${rp}`,
    jagaAktif: "Active",
    jagaSimpan: "Save",
    jagaMenyimpan: "Saving…",
    jagaTersimpan: "Saved ✓",
    jagaGagal: "Couldn't save — try again.",
    belumBayar: "No payments yet.",
    manjatLagi: "Climb again",
    stabil: "stable",
    perHari: (rp: string) => `${rp}/day`,
    perKlik: (rp: string) => `${rp}/click`,
    totalKlik: (n: number) => `total ${n}`,
    cpcSub: "slip cost ÷ clicks today",
    cpcBelum: "no clicks yet",
    bertahanHari: (n: number) => `~${n} days`,
  },

  admin: {
    judulAntrean: "Moderation queue",
    keluar: "Log out",
    menunggu: (n: number) => `${n} listings awaiting a decision.`,
    kosong: "Queue empty.",
    loloskan: "Approve",
    tolak: "Reject + refund",
    laporanJudul: (n: number) => `Reports & claims (${n})`,
    tidakAdaLaporan: "No open reports.",
    turunkan: "Take down + refund",
    tutupLaporan: "Close report",
    klaimUrl: "URL CLAIM",
    laporan: "REPORT",
    alasan: (a: string) => `Reason: ${a}`,
    masukJudul: "Admin",
    passwordPlaceholder: "Admin password",
    kode2fa: "2FA code (6 digits)",
    masuk: "Log in",
  },

  lapor: {
    judul: "Report / claim",
    metaTitle: "Report / claim — Panjat",
    intro: (nama: string) =>
      `Listing: ${nama}. Reports are decided by a human. The rightful owner of a URL may request the takedown of the listing for their URL.`,
    jenis: "Type",
    jenisLapor: "Report problem content",
    jenisKlaim: "Claim: I own this URL",
    pesan: "Message",
    pesanPlaceholder: "Briefly describe the problem or your proof of URL ownership…",
    kontak: "Your contact (to verify the claim)",
    kontakPlaceholder: "email",
    kirim: "Send",
    kembali: "← Back",
  },

  footer: [
    ["/aturan", "Rules"],
    ["/arsip", "Champions Archive"],
    ["/statistik", "Stats"],
    ["/privasi", "Privacy"],
    ["/ketentuan", "Terms"],
  ],

  /**
   * Errors: what happened → consequence → what to do. Plain and literal.
   */
  error: {
    urlWajib: "The URL is empty. We need your product's address to list it — paste the URL first.",
    bodyTidakValid: "The submitted data couldn't be read. Try again from the start.",
    listingTidakDitemukan: "This listing doesn't exist or is no longer live. Refresh the board and try again.",
    nominalWajib: "The amount is empty. Enter how much you want to pay.",
    emailTidakValid: "That email doesn't look right. Example: you@email.com",
    gagalProses: "Processing failed. Try again in a moment.",
    gagalHitung: "Couldn't calculate the position. Check your connection and try again.",
    gagalTagihan: "Couldn't create the invoice. Payment hasn't started — try again in a moment.",
    tautanKedaluwarsa: "The link is invalid or has expired. Request a new link to log in.",
    passwordSalah: "Wrong password. Try again.",
    terlaluBanyak: "Too many attempts. Wait a moment before trying again.",
    kunjunganTakDikenal: "Your visit isn't recognized yet. Reload the page and try again.",
    sudahVoteHariIni: "You've already voted today. You can vote again tomorrow.",
    terlaluBanyakPermintaan: "Too many requests. Wait a moment and try again.",
    terlaluBanyakGratis: "Too many free listings from here. Try again later.",
    targetTidakDikenal: "The target position isn't recognized. Pick the target again.",
    targetWajib: "Pick a target position or enter an amount first.",
    urlTidakValid: "The URL is invalid. Double-check the address and try again.",
  },

  /**
   * WhatsApp/email templates (R3). Keep money-plain; always include the
   * one-click "climb again" and unsubscribe links.
   */
  notif: {
    unsubBerhenti: "Unsubscribe",
    unsubTidakValid: "Invalid link",
    unsubBerhasil:
      "You won't receive overtaken notifications anymore. Your position is still visible on the board any time.",
    unsubGagal: "The unsubscribe link isn't recognized or has expired.",
    unsubKePapan: "To the board",
    disalipSubjek: "You've been overtaken on Panjat",
    disalip: (d: { toRank: number; tierLabel: string; pegangan: number; manjatLink: string; unsubLink: string }) => {
      const headline = `You slipped to #${d.toRank}, dropping out of ${d.tierLabel}.`;
      return {
        headline,
        email:
          `${headline}\nYour grip is now ${formatRupiah(d.pegangan)}.\n` +
          `Climb again: ${d.manjatLink}\nUnsubscribe: ${d.unsubLink}`,
        wa: `${headline} Climb again: ${d.manjatLink}`,
      };
    },
  },

  /** Dev-only mock payment page (stand-in for the real gateway). */
  bayarMock: {
    modeUji: "TEST MODE",
    berhasilJudul: "You're on the board!",
    berhasilPesan: (rp: string) =>
      `Payment ${rp} confirmed. Your listing is now live on the board.`,
    lihatPosisi: "See your spot on the board →",
    judul: "Simulated payment",
    total: "Total",
    gagal: (msg: string) => `Failed: ${msg}`,
    bayar: "Pay now (simulated)",
    memproses: "Processing…",
    batal: "Cancel",
  },

  /** System pages — 404 / error boundary / loading. Plain and reassuring. */
  sistem: {
    memuat: "Loading…",
    lompatKeIsi: "Skip to content",
    takAdaJudul: "Page not found",
    takAdaPesan: "The link might be wrong or the listing is no longer live.",
    galatJudul: "Something stalled",
    galatPesan: "Sorry, a brief hiccup. Try again in a moment.",
    cobaLagi: "Try again",
    kePapan: "To the board",
    tutup: "Close",
  },
};
