/**
 * Central copy deck (R20-c). Every user-facing string — UI labels, error
 * messages, and WhatsApp/email templates — lives here, not inline in components.
 * Tone follows §10.2: marketing surfaces may be playful; money surfaces
 * (payment, amounts, rules, dashboard, errors) stay plain and literal. The
 * retired "api/bara" fire vocabulary must never reappear.
 *
 * Error messages follow the pattern: what happened → consequence → what to do.
 * Never a bare error code.
 */
import { formatRupiah } from "@/lib/format";

export const copy = {
  merek: {
    nama: "Panjat",
    tagline: "Rebut Peringkat Teratas",
    deskripsiSitus:
      "Tempel linkmu, panjat papan, dan salip yang di atas. Makin kuat peganganmu, makin tinggi posisimu.",
  },

  nav: {
    sepanjangMasa: "Papan Utama",
    hariIni: "Hari Ini",
    jelajah: "Jelajah",
    cari: "Cari",
    manjat: "Manjat",
    leaderboard: "Leaderboard",
    statistik: "Statistik",
    arsip: "Arsip",
    aturan: "Aturan",
    papanRingkas: "Papan",
  },

  beranda: {
    heroJudul: "Panjat. Salip. Jadi #1.",
    statOnline: "online",
    statPengunjung: "pengunjung",
    lihatStatistik: "Lihat statistik →",
    tabSepanjang: "All time",
    papanKosongJudul: "Belum ada yang manjat.",
    papanKosongPesan: "Tiangnya masih kinclong.",
    papanKosongCta: "Jadi yang pertama naik tiang",
    caraMainJudul: "Cara main",
    punyaProduk: "Punya produk?",
    heroUrlPlaceholder: "Tempel link yang mau kamu panjatkan",
    heroKategoriPlaceholder: "Kategori",
    heroCta: "Mulai Panjat",
  },

  caraMain: [
    ["1", "Tempel link produkmu", "Judul, deskripsi, dan kategori terisi otomatis."],
    ["2", "Pilih posisi & bayar", "Sistem yang menghitung rupiahnya. Bayar lewat QRIS/e-wallet."],
    ["3", "Naik — lalu merosot", "Tiangnya licin, semua turun pelan. Manjat lagi kalau mau bertahan."],
  ] as const,

  listing: {
    pratinjauAlt: (nama: string) => `Pratinjau situs ${nama}`,
  },

  papan: {
    aktivitas: "Aktivitas",
    aktivitasVote: "baru divote",
    aktivitasDukung: "baru didukung",
    aktivitasManjat: "baru manjat",
    aktivitasNaik: (rank: number) => `naik ke #${rank}`,
    aktivitasKali: (n: number) => ` ${n}x`,
    puncakBerganti: (nama: string) => `Puncak berganti — ${nama} kini #1`,
    papanDiperbarui: "Papan diperbarui",
    koneksiPutus: "Koneksi papan live terputus — mencoba menyambung…",
    bukaTabBaru: "buka di tab baru",
    juaraKakiTiang: "Juara Kaki Tiang minggu ini · gratis",
    juaraTerfavorit: "Pemanjat terfavorit pekan lalu",
    juaraTerfavoritVote: (n: number) => `${n.toLocaleString("id-ID")} vote`,
    terfavoritPekanIni: "Terfavorit pekan ini",
    dukunganTerbanyak: "Dukungan terbanyak",
    salip: (rp: string) => `Salip ${rp}`,
    salipRank: (rank: number, rp: string) => `Salip #${rank} ${rp}`,
    juara: (rank: number) => `Juara ${rank}`,
    salipSingkat: "Salip",
    klik: (n: number) => `${n.toLocaleString("id-ID")} klik`,
    klikProof: "Klik nyata yang sudah dikirim ke situs ini — dihitung di server.",
    // Card rosot status (revealed on hover) — two states + the at-floor case.
    rosotTerjaga: "masih terjaga",
    rosotAktif: (rp: string) => `merosot ~${rp}/hari`,
    rosotLantai: "di lantai · tak merosot",
    kunjungiSitus: "Kunjungi situs",
    salipDiPapan: "Salip di papan",
    pagination: (hal: number, total: number) => `Halaman ${hal} / ${total}`,
    sebelumnya: "← Sebelumnya",
    berikutnya: "Berikutnya →",
  },

  manjat: {
    judul: "Naik tiang",
    kembaliPapan: "← Papan",
    steps: ["Detail", "Posisi", "Bayar"],
    urlLabel: "URL",
    urlPlaceholder: "panjat.id",
    detailTerisi: "Detail terisi",
    cekLink: "Mengecek link & mengisi detail…",
    hapusUrl: "Hapus & tulis ulang",
    detailRingkas: "Judul, kategori & deskripsi — ketuk untuk ubah",
    posisiPrimer: "Kamu akan bayar",
    judulListing: "Judul",
    judulPlaceholder: "Nyala Analytics",
    kategori: "Kategori",
    deskripsi: "Deskripsi (160 kar.)",
    emailOpsional: "Email (opsional)",
    emailPlaceholder: "kamu@email.com",
    emailHint: "Isi kalau mau akses dasbor & notifikasi. Tanpa akun.",
    lanjut: "Lanjut",
    kembali: "Kembali",
    kembaliPosisi: "Kembali ke posisi",
    detail: "Detail",
    ubahDetail: "ubah detail",
    manjatPrefix: "Manjat:",
    posisiTanya: "Mau di posisi berapa? Sistem yang menghitung.",
    pratinjauSitus: "Pratinjau situsmu",
    pratinjauAlt: (nama: string) => `Pratinjau situs ${nama}`,
    nominalLabel: "Nominal (Rp)",
    nominalPlaceholder: "25.000",
    nominalTanya: "Mau bayar berapa? Posisi dihitung otomatis.",
    nominalNaik: "Makin besar bayarannya, makin tinggi posisimu. Minimal Rp5.000.",
    manjatLagiHint: (saatIni: string, total: string) =>
      `Manjat lagi — pegangan ${saatIni} + bayaranmu jadi ${total}.`,
    nominalDinaikkan: (rp: string) => `Di bawah minimum — otomatis dinaikkan ke ${rp}.`,
    diPosisi: "Kamu akan di posisi",
    ketikNominal: "Ketik nominal untuk lihat posisimu di papan.",
    kamuBadge: "kamu",
    listingKamu: "Listing kamu",
    salipTambah: (extra: string, rank: number) => `Tambah ${extra} → salip #${rank}`,
    jadiPuncak: "🚩 Kamu jadi #1 — puncak!",
    papanPratinjau: "Posisimu di papan",
    posisiRingkas: (rosot: string, estimasiHari: number | null) =>
      `Merosot ~${rosot}/hari · ` +
      (estimasiHari === null ? "stabil (kaki tiang)" : `bertahan ~${estimasiHari} hari`),
    akanBayar: "Kamu akan bayar",
    bayar: (rp?: string) => (rp ? `Bayar ${rp}` : "Bayar"),
    bayarMinimal: (rp: string) => `Bayar minimal ${rp}`,
    consentSetuju: "Saya setuju dengan",
    consentKetentuan: "Ketentuan",
    consentAturan: "Aturan main",
    consentRosot: ", dan paham pegangan bisa rosot (turun) seiring waktu.",
    bayarQris: (rp: string) => `Bayar ${rp} lewat QRIS`,
    memproses: "Memproses…",
    menghitung: "Menghitung…",
    pilihTarget: "Pilih target posisi.",
    yakinBayar: (rp: string) => `Saya yakin membayar ${rp}.`,
    diprosesJudul: "Pembayaran diproses",
    diprosesPesan: "Posisimu akan muncul di papan begitu pembayaran dikonfirmasi.",
    kePapan: "Ke papan",
    // Quote summary line under the amount selector.
    quoteRingkas: (rank: number, rosotRp: string, estimasiHari: number | null) =>
      `Posisi #${rank} · merosot ~${rosotRp}/hari · ` +
      (estimasiHari === null ? "stabil (kaki tiang)" : `bertahan ~${estimasiHari} hari`),
    ringkasListing: "Listing",
    ringkasTarget: "Target posisi",
    ringkasEstimasi: "Estimasi bertahan",
    ringkasTotal: "Total",
    stabil: "stabil",
    bertahanHari: (n: number) => `~${n} hari`,
  },

  favorit: {
    judul: "Pemanjat terfavorit",
    hadiah: "Juara ditentukan tiap Rabu 17.00 WIB, diposting di Threads & TikTok tiap Jumat.",
    labelBelumVote: "vote gratis · 1×/hari",
    sudahVote: "sudah vote",
    ajakan: "Pilih favoritmu — bukan soal uang, soal selera. Sekali sehari.",
    pilihListing: "Pilih listing…",
    pilihLainnya: "Pilih lainnya",
    pilihJudul: "Pilih pemanjat",
    terpilih: "Pilihanmu",
    batalPilih: "Batalkan pilihan",
    cari: "Cari pemanjat…",
    takAda: "Tidak ada listing yang cocok.",
    vote: "Vote",
    voteMengirim: "Mengirim…",
    voteGagal: "Gagal menyimpan vote — coba lagi.",
    vote_n: (n: number) => `${n.toLocaleString("id-ID")} vote`,
    belumAda: "Jadilah yang pertama menerima suara.",
  },

  kakiTiang: {
    judul: "Kaki Tiang",
    sisaDukungan: (n: number) => `${n} dukungan tersisa hari ini`,
    ajakan:
      "Listing gratis — dukung yang menurutmu bagus. Tiap Rabu, yang paling banyak didukung jadi Juara Kaki Tiang dan naik tampil di papan.",
    dukung: "Dukung",
    dukungGagal: "Gagal dukung — coba lagi.",
    dukungan_n: (n: number) => `${n.toLocaleString("id-ID")} dukungan`,
    kosong: "Belum ada yang nunggu, kamu gak ada pesaing",
    pasangGratisTaut: "Pasang gratis di Kaki Tiang",
    baruNaik: "Listingmu sudah naik ke Kaki Tiang. Ajak orang buat dukung biar naik!",
    baruTutup: "Tutup",
  },

  momen: {
    eyebrow: "Momen Puncak",
    dipuncak: "Kamu di puncak!",
    naik: (rank: number) => `Kamu naik ke #${rank}`,
    ringkas: (nama: string, pegangan: string) => `${nama} · pegangan ${pegangan}`,
    menyalip: (n: number) => `menyalip ${n} pemanjat`,
    share: (rank: number) => `Aku #${rank} di Panjat!`,
    kartuAlt: (nama: string) => `Kartu ${nama}`,
    siapkanPratinjau: "Menyiapkan pratinjau…",
    bagikanAjak: "Simpan & pamerkan 👇",
    lihatPapan: "Lihat leaderboard",
    pilihUkuran: "Pilih ukuran kartu",
    unduh: "Unduh kartu",
    mengunduh: "Menyiapkan…",
    tersimpan: "Kartu tersimpan ✓",
    bagikan: "Bagikan",
    tautanDisalin: "Tautan disalin ✓",
    toggleScreenshot: "Screenshot",
    toggleLogo: "Logo",
    rasio: "Rasio",
    gambar: "Gambar",
  },

  privasi: {
    metaTitle: "Kebijakan Privasi — Panjat",
    judul: "Kebijakan Privasi",
    butir: [
      ["Yang kami simpan.", " Kontak kamu (email) untuk dasbor dan notifikasi. Untuk klik, kami hanya menyimpan versi teracak dari alamat IP-mu — bukan IP aslinya — jadi tidak bisa dilacak balik ke kamu. Fitur penonton memakai cookie anonim yang tidak menyimpan data pribadi apa pun."],
      ["Berapa lama kami simpan.", " Data klik mentah kami hapus setelah 13 bulan; yang tersimpan permanen hanya rekap hariannya. Catatan notifikasi disimpan 6 bulan. Data transaksi kami simpan selama masih diwajibkan untuk pajak dan audit."],
      ["Hak kamu.", " Kamu bebas berhenti menerima notifikasi kapan saja, dan boleh minta data kontakmu dihapus — tinggal kabari kami."],
    ] as const,
    kontak: "Mau hapus data atau ada pertanyaan soal privasi? Email kami di halo@panjat.id.",
    diperbarui: "Terakhir diperbarui 30 Agustus 2026.",
  },

  ketentuan: {
    metaTitle: "Syarat & Ketentuan — Panjat",
    judul: "Syarat & Ketentuan",
    peganganTebal: "Pegangan & refund.",
    peganganSisa:
      " Peringkat kamu ditentukan oleh pegangan. Pegangan yang sudah dibayar tidak bisa di-refund — kecuali listing-mu ditolak moderasi; kalau itu terjadi, dana kembali penuh. Detailnya ada di halaman ",
    peganganLink: "Aturan",
    butir: [
      ["Moderasi & konten.", " Konten judi/slot, dewasa, pinjol ilegal, dan penipuan tidak kami terima. Kalau ada listing yang melanggar, kami bisa menahan atau menurunkannya."],
      ["Kepemilikan URL.", " Kalau kamu pemilik sah sebuah URL, kamu berhak mengklaim listing-nya atau minta listing itu diturunkan. Kami perlu verifikasi dulu."],
      ["Tanggung jawab.", " Panjat hanya menampilkan listing — isi dan produk sepenuhnya tanggung jawab masing-masing sponsor."],
      ["Kontak.", " Ada pertanyaan soal ketentuan ini? Email kami di halo@panjat.id."],
    ] as const,
    diperbarui: "Terakhir diperbarui 30 Agustus 2026.",
  },

  jelajah: {
    cariPlaceholder: "Cari AI tools, jasa, game…",
    cari: "Cari",
    cariLabel: "Cari listing",
    kembali: "← Kembali ke Cari",
    juaraKategori: "Juara kategori",
    diPapan: "di papan →",
    lihatDetail: "Lihat detail →",
    semua: "Semua",
    kosong: "Tidak ada listing yang cocok. Coba kata kunci atau kategori lain.",
  },

  hariIni: {
    judul: "Papan Hari Ini",
    kosong: "Belum ada yang membayar hari ini. Juara hari ini masih terbuka lebar.",
    metaTitle: "Papan Hari Ini — Panjat",
    metaDesc: "Papan yang reset tiap tengah malam WIB. Siapa pun bisa juara hari ini.",
  },

  statistik: {
    judul: "Statistik",
    sub: "Angka apa adanya buat kamu timbang sebelum manjat. Semua publik, langsung dari data kami sendiri.",
    diperbarui: (waktu: string) => `Diperbarui ${waktu} WIB · dihitung ulang tiap kali halaman ini dibuka`,
    metaTitle: "Statistik — Panjat",
    metaDesc: "Angka-angka publik Panjat buat kamu yang mau manjat: harga puncak sekarang, biaya masuk 20 besar, klik seminggu terakhir, CPC, jumlah sponsor, dan seberapa sering puncak berganti.",
    hargaPuncak: "Harga puncak sekarang",
    hargaPuncakSub: "buat duduk di #1",
    hargaPuncakMetode: "Pegangan yang sekarang dipegang juara #1, diambil dari catatan pembayaran.",
    hargaMasuk20: "Biaya masuk 20 besar",
    hargaMasuk20Sub: "pegangan peringkat ke-20",
    hargaMasuk20Metode: "Pegangan listing yang sekarang duduk di peringkat ke-20.",
    hargaMasuk20Terbuka: "Masih terbuka",
    hargaMasuk20TerbukaSub: "slot 20 besar belum penuh",
    klik7: "Klik 7 hari terakhir",
    klik7Sub: (perHari: string) => `± ${perHari}/hari`,
    klik7Metode: "Dihitung di server tiap ada yang klik link. Klik berulang dari orang yang sama dalam 6 jam tidak dihitung dobel.",
    cpc: "CPC rata-rata",
    cpcSub: "rupiah per klik terkirim",
    cpcMetode: "Total uang masuk yang terverifikasi dibagi jumlah klik link, dihitung sejak hari pertama.",
    sponsor: "Sponsor aktif",
    sponsorSub: "sedang tayang di papan",
    sponsorMetode: "Jumlah listing yang sedang tayang di papan sekarang.",
    puncakBerganti: "Puncak berganti (7 hari)",
    puncakBergantiSub: "makin sering, makin gampang direbut",
    puncakBergantiMetode: "Berapa kali posisi #1 berganti tangan, dari rekaman posisi tiap jam.",
    pengunjung: "Total pengunjung",
    pengunjungSub: "jangkauan sejak awal",
    pengunjungMetode: "Jumlah pengunjung berbeda, dihitung lewat cookie anonim yang aman — tanpa menyimpan data pribadi.",
    online: "Online sekarang",
    onlineSub: "lagi lihat papan",
    onlineMetode: "Pengunjung yang aktif dalam beberapa menit terakhir.",
    ga4Lokasi: "Lokasi pengunjung",
    ga4Perangkat: "Perangkat",
    ga4Sumber: "Data ini berasal dari Google Analytics",
  },

  arsip: {
    judul: "Arsip Juara",
    sub: "Posisi disewa, tapi sejarah permanen. Setiap juara harian tersimpan selamanya.",
    metaTitle: "Arsip Juara — Panjat",
    metaDesc: "Setiap juara harian, tersimpan permanen.",
    kosong: "Belum ada juara yang diarsipkan.",
    mingguanJudul: "Juara minggu ini",
    mingguanPekan: (minggu: string) => `Pekan ${minggu}`,
    mingguanInfo: "Diperbarui otomatis tiap pekan, diarsipkan permanen.",
    harianJudul: "Juara harian",
    jenis: {
      papan1: "Juara 1",
      papan2: "Juara 2",
      papan3: "Juara 3",
      terfavorit: "Terfavorit",
      kaki_tiang: "Juara Kaki Tiang",
    } as Record<string, string>,
  },

  aturan: {
    metaTitle: "Aturan — Panjat",
    metaDesc: "Cara kerja tiang licin — seberapa cepat kamu merosot di tiap posisi, contoh angkanya, plus aturan soal peringkat dan refund.",
    judul: "Aturan",
    intro:
      "Kamu bayar untuk manjat, dan yang pegangannya paling kuat duduk paling atas. Tapi tiangnya licin: pelan-pelan semua orang merosot. Kalau mau bertahan di atas, tinggal manjat lagi.",
    tabelJudul: "Seberapa cepat kamu merosot tiap hari",
    kolomPosisi: "Posisi",
    kolomRosot: "Rosot / hari",
    tierR1: "#1 (puncak)",
    tierR2_3: "#2–3",
    tierR4_10: "#4–10",
    tierR11_30: "#11–30",
    tierR31: "#31 ke bawah",
    tierKaki: (rp: string) => `Pegangan ≤ ${rp} (Kaki Tiang)`,
    contoh: (grip: string, rosot: string, sisa: string) =>
      `Contoh: pegangan ${grip} di #1 merosot ${rosot} per hari. Kalau kamu berhenti manjat, dalam ~5 hari tinggal ~${sisa} — dan puncak kembali terbuka buat orang lain.`,
    peringkatTebal: "Peringkat murni ditentukan pegangan.",
    peringkatSisa: " Tidak ada algoritma tersembunyi, dan tidak ada posisi yang dijual diam-diam di luar sistem.",
    refundTebal: "Tidak ada refund",
    refundSisa: " untuk pegangan yang sudah kamu bayar — kecuali kalau listing-mu ditolak moderasi; kalau itu terjadi, dana kembali penuh.",
    rosotServer: (rp: string) =>
      `Rosot dihitung otomatis di server tiap jam. Pegangan berhenti merosot begitu menyentuh ${rp} (Kaki Tiang), dan listing-mu tidak akan pernah dihapus hanya karena merosot.`,
    lantaiTebal: "Yang sudah kamu bayar dilindungi.",
    lantaiSisa: (persen: string, maks: string) =>
      ` Peganganmu tidak akan melorot di bawah ${persen} dari total yang kamu bayar (maksimal ${maks}). Jadi sekali bayar, kamu tidak akan jatuh ke dasar — tapi puncak tetap harus diperjuangkan.`,
  },

  pasangGratis: {
    judul: "Pasang gratis",
    subJudul: "Listing gratis di Kaki Tiang, diurut dukungan pengunjung.",
    urlPlaceholder: "produkku.id",
    judulPlaceholder: "Produkku",
    emailHint: "Isi kalau mau kelola listing nanti.",
    tombol: "Pasang di Kaki Tiang",
    sisaSlot: (sisa: number, total: number) =>
      `Siapa cepat — sisa ${sisa} dari ${total} slot gratis minggu ini.`,
    penuh: "Slot gratis minggu ini sudah penuh. Coba lagi minggu depan, atau naik tiang berbayar.",
  },

  dasbor: {
    judul: "Dasbor",
    keluar: "Keluar",
    belumAdaListing: "Belum ada listing atas akun ini.",
    manjatSekarang: "Manjat sekarang",
    masukJudul: "Masuk dasbor",
    masukSub: "Pantau pegangan, klik, dan CPC listing kamu.",
    statPegangan: "Pegangan",
    statPosisi: "Posisi",
    statRosot: "Laju rosot",
    statEstimasi: "Estimasi bertahan",
    statKlik: "Klik hari ini",
    statCpc: "CPC",
    posisi7: "Posisi 7 hari",
    pratinjauSitus: "Pratinjau situs",
    segarkan: "Segarkan pratinjau",
    menyegarkan: "Menyegarkan…",
    pratinjauTersegarkan: "Pratinjau diperbarui ✓",
    belumAdaPratinjau: "Belum ada pratinjau. Segarkan untuk menangkap tampilan situsmu.",
    deskripsi: "Deskripsi",
    riwayat: "Riwayat pembayaran",
    jagaJudul: "Jaga posisi otomatis",
    jagaKet: "Sistem otomatis manjat lagi kalau kamu merosot di bawah target — pakai kartu/e-wallet berulang, bukan saldo. Berhenti kapan saja.",
    jagaTarget: "Target",
    jagaTop1: "Tetap #1",
    jagaTop3: "Tetap Top 3",
    jagaTop10: "Tetap Top 10",
    jagaBudget: "Tambah budget (Rp)",
    jagaSisa: (rp: string) => `Sisa budget: ${rp}`,
    jagaAktif: "Aktif",
    jagaSimpan: "Simpan",
    jagaMenyimpan: "Menyimpan…",
    jagaTersimpan: "Tersimpan ✓",
    jagaGagal: "Gagal menyimpan — coba lagi.",
    belumBayar: "Belum ada pembayaran.",
    manjatLagi: "Manjat lagi",
    stabil: "stabil",
    perHari: (rp: string) => `${rp}/hari`,
    perKlik: (rp: string) => `${rp}/klik`,
    totalKlik: (n: number) => `total ${n}`,
    cpcSub: "biaya rosot ÷ klik hari ini",
    cpcBelum: "belum ada klik",
    bertahanHari: (n: number) => `~${n} hari`,
  },

  admin: {
    judulAntrean: "Antrean moderasi",
    keluar: "Keluar",
    menunggu: (n: number) => `${n} listing menunggu keputusan.`,
    kosong: "Antrean kosong.",
    loloskan: "Loloskan",
    tolak: "Tolak + refund",
    laporanJudul: (n: number) => `Laporan & klaim (${n})`,
    tidakAdaLaporan: "Tidak ada laporan terbuka.",
    turunkan: "Turunkan + refund",
    tutupLaporan: "Tutup laporan",
    klaimUrl: "KLAIM URL",
    laporan: "LAPORAN",
    alasan: (a: string) => `Alasan: ${a}`,
    masukJudul: "Admin",
    passwordPlaceholder: "Password admin",
    kode2fa: "Kode 2FA (6 digit)",
    masuk: "Masuk",
  },

  lapor: {
    judul: "Laporkan / klaim",
    metaTitle: "Laporkan / klaim — Panjat",
    intro: (nama: string) =>
      `Listing: ${nama}. Laporan diputus manusia. Pemilik sah URL berhak meminta penurunan listing atas URL-nya.`,
    jenis: "Jenis",
    jenisLapor: "Laporkan konten bermasalah",
    jenisKlaim: "Klaim: saya pemilik URL ini",
    pesan: "Pesan",
    pesanPlaceholder: "Ceritakan singkat masalahnya atau bukti kepemilikan URL…",
    kontak: "Kontak kamu (untuk verifikasi klaim)",
    kontakPlaceholder: "email",
    kirim: "Kirim",
    kembali: "← Kembali",
  },

  footer: [
    ["/aturan", "Aturan"],
    ["/arsip", "Arsip Juara"],
    ["/statistik", "Statistik"],
    ["/privasi", "Privasi"],
    ["/ketentuan", "Ketentuan"],
  ] as const,

  /**
   * Errors: what happened → consequence → what to do. Plain and literal.
   */
  error: {
    urlWajib: "URL belum diisi. Kami butuh alamat produkmu untuk memasangnya — tempel dulu URL-nya.",
    bodyTidakValid: "Data yang dikirim tidak terbaca. Coba ulangi dari awal.",
    listingTidakDitemukan: "Listing ini tidak ada atau sudah tidak tayang. Segarkan papan lalu coba lagi.",
    nominalWajib: "Nominal belum diisi. Masukkan jumlah rupiah yang mau kamu bayar.",
    gagalProses: "Gagal memproses. Coba lagi sebentar lagi.",
    gagalHitung: "Gagal menghitung posisi. Cek koneksi lalu coba lagi.",
    gagalTagihan: "Gagal membuat tagihan. Pembayaran belum berjalan — coba lagi sebentar lagi.",
    tautanKedaluwarsa: "Tautan tidak valid atau sudah kedaluwarsa. Minta tautan baru untuk masuk.",
    passwordSalah: "Password salah. Coba lagi.",
    terlaluBanyak: "Terlalu banyak percobaan. Tunggu sebentar sebelum mencoba lagi.",
    kunjunganTakDikenal: "Kunjunganmu belum dikenali. Muat ulang halaman lalu coba lagi.",
    sudahVoteHariIni: "Kamu sudah vote hari ini. Besok bisa vote lagi.",
    terlaluBanyakPermintaan: "Terlalu banyak permintaan. Tunggu sebentar lalu coba lagi.",
    terlaluBanyakGratis: "Terlalu banyak listing gratis dari sini. Coba lagi nanti.",
    targetTidakDikenal: "Target posisi tidak dikenal. Pilih ulang targetnya.",
    targetWajib: "Pilih target posisi atau isi nominal dulu.",
    urlTidakValid: "URL tidak valid. Cek lagi alamatnya lalu coba lagi.",
  },

  /**
   * WhatsApp/email templates (R3). Keep money-plain; always include the
   * one-click "manjat lagi" and unsubscribe links.
   */
  notif: {
    unsubBerhenti: "Berhenti berlangganan",
    unsubTidakValid: "Tautan tidak valid",
    unsubBerhasil:
      "Kamu tidak akan menerima notifikasi disalip lagi. Posisimu tetap bisa dilihat di papan kapan saja.",
    unsubGagal: "Tautan berhenti berlangganan tidak dikenali atau kedaluwarsa.",
    unsubKePapan: "Ke papan",
    disalipSubjek: "Kamu disalip di Panjat",
    disalip: (d: { toRank: number; tierLabel: string; pegangan: number; manjatLink: string; unsubLink: string }) => {
      const headline = `Kamu merosot ke #${d.toRank}, keluar dari ${d.tierLabel}.`;
      return {
        headline,
        email:
          `${headline}\nPeganganmu sekarang ${formatRupiah(d.pegangan)}.\n` +
          `Manjat lagi: ${d.manjatLink}\nBerhenti berlangganan: ${d.unsubLink}`,
        wa: `${headline} Manjat lagi: ${d.manjatLink}`,
      };
    },
  },

  /** System pages — 404 / error boundary / loading. Plain and reassuring. */
  sistem: {
    memuat: "Memuat…",
    lompatKeIsi: "Lompat ke konten",
    takAdaJudul: "Halaman tidak ditemukan",
    takAdaPesan: "Tautannya mungkin salah atau listingnya sudah tidak tayang.",
    galatJudul: "Ada yang tersendat",
    galatPesan: "Maaf, ada gangguan sesaat. Coba lagi sebentar.",
    cobaLagi: "Coba lagi",
    kePapan: "Ke papan",
  },
} as const;
